services:
  - type: web
    name: kaufland-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: RENDER
        value: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 